package com.throne.seckilling.dao;

import com.throne.seckilling.data_object.StockLogDO;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StockLogDOMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    int insert(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    int insertSelective(StockLogDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    StockLogDO selectByPrimaryKey(String stockLogId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    int updateByPrimaryKeySelective(StockLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri May 22 09:58:05 CST 2020
     */
    int updateByPrimaryKey(StockLogDO record);
}