package com.throne.seckilling.data_object;

public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrypt_pwd
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    private String encryptPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrypt_pwd
     *
     * @return the value of user_password.encrypt_pwd
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public String getEncryptPwd() {
        return encryptPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrypt_pwd
     *
     * @param encryptPwd the value for user_password.encrypt_pwd
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public void setEncryptPwd(String encryptPwd) {
        this.encryptPwd = encryptPwd == null ? null : encryptPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Fri Apr 10 00:17:42 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}